name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */6 * * *' # На всеки 6 часа
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit
        run: |
          curl -sL "https://yo-crm.streamlit.app" > /dev/null
